### ISSUE TITLE
what's  the final solution of issue #7?

### ISSUE THREAD

**Issue by kinovlee** [t-mullen/video-stream-merger#10]
https://github.com/RationalCoding/video-stream-merger/issues/7 
this issue seems have not really solved. what's the final solution?

**Comment by t-mullen** [comment]
I don't have a Wowza instance so I assumed his solution worked. Are you seeing this problem without Wowza?

**Comment by kinovlee** [comment]
If all source disconnect from MediaStreamDestination ,it will stop sending audio stream data, and that will cause decoder  side  crash. I've tested by using ffmpeg.That is to say, const audio stream is a must. I modify the code base on xiang-valcano 's and audio quality is ok.

var constantAudioNode = self._audioCtx.createConstantSource()
        constantAudioNode.start()
        var gain = self._audioCtx.createGain()
        gain.gain.value=0
        constantAudioNode.connect(gain)
        gain.connect(self._audioDestination)

**Comment by t-mullen** [comment]
Okay, well if you aren't seeing a drop in audio quality, I would use that solution.

Are you using Wowza?

**Comment by t-mullen** [comment]
I see you've added a gain node as well. I'll try that.

**Comment by t-mullen** [comment]
It works. Thanks. `v2.5.1`
