### ISSUE TITLE
Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6)

### ISSUE THREAD

**Issue by wangjunji** [t-mullen/video-stream-merger#11]
I've to refresh the video merger stream in my application. I implement this feature by reinstantiating the merger object. However, destroying the merger up to 6 times will cause the error.

Solution:

Add 

` self._audioCtx.close()`

Before 

https://github.com/RationalCoding/video-stream-merger/blob/gh-pages/src/index.js#L202

It will release the hardware of the context while ` self._audioCtx = null` won't

**Comment by t-mullen** [comment]
Thank you! I was wondering if there was a way to clean up the AudioContext. I'll make the change, or feel free to PR.
