### ISSUE TITLE
Method to update a video stream

### ISSUE THREAD

**Issue by wangjunji** [t-mullen/video-stream-merger#12]
Need a method to update a stream in my live streaming app ,the position and size of the video stream may be dynamically changed by user,the api should look like:

`merger.updateStream(id|MediaStream,opt)`

BTW, Is there a `z(-index)` option to control the overlap order of video stream ? 

Thanks for the good library.

**Comment by t-mullen** [comment]
The position and size options are just convenient wrappers around the `draw` API, so you can change them through that.

```javascript
var myOpts = {x: 0, y:0, width: 100, height:100}
merger.addStream(mediaStream, {
  draw: function (ctx, frame, done) {
    ctx.drawImage(frame, myOpts.x, myOpts.y, myOpts.width, myOpts.height)
    done()
  })
})

// changes to myOpts will be applied on next frame draw
myOpts.x = 10
myOpts.width = 200
```

The z-index option is called `index`. It is the order in which to draw the stream (0 pushes to bottom, null pushes to top, -1 to second-from-top, etc.). The streams drawn first will be on the bottom.

**Comment by wangjunji** [comment]
Thanks.

**Comment by wangjunji** [comment]
Sorry to reopen the issue. 
I've checked that changes to position and  size options (x,y,weight,height) will be applied on next frame draw as you said, but it seems that change to index doesn't work. How can I change the draw order of video stream dynamically?

**Comment by t-mullen** [comment]
Hmmmm... I don't think there is a way. I'll take a look at implementing `updateStream`.

**Comment by t-mullen** [comment]
`2.6.1` now has the `merger.updateIndex(mediaStream|id, newIndex)` method.

Index is the only option that isn't covered by draw and audioEffect, so I think this handles things nicely without too much complexity.
