### ISSUE TITLE
Non-issue: Cordova comparability?

### ISSUE THREAD

**Issue by alectrocute** [t-mullen/video-stream-merger#13]
Hey @RationalCoding,

Before I spend hours trying (and possibly failing), would video-stream-merger be able to combine a .mp4 video with a .wav (or AAC) file of the same length on Cordova (iOS and Android)?

Feel free to close this after answering.

Thanks so much!

**Comment by t-mullen** [comment]
Yes, the draw and audioEffect apis should be enough to allow that. You'll need the media playing in an <audio> or <video> element first.

```javascript
var videoElement = document.querySelector('video')
```

You'll need to merge video by drawing the element onto the merging canvas directly:

```javascript
function myCustomDraw (ctx, _, done) {
   ctx.drawImage(videoElement, x, y, width, height) // you'll need to specify these position variables (they are identical to the options in the normal API)
  done() // always call this or merging can't continue
}
```

Audio is merged with WebAudio:
```javascript
var audioSource = merger.getAudioContext().createMediaElementSource(videoElement) 
function myCustomAudio(_, destination) {
  audioSource.connect(destination)
}
```

Add a "data stream" APIs (which don't add any of the overhead for MediaStream input, since you have none) with these custom options.
```javascript
merger.addStream('myMp4Stream' {
  draw: myCustomDraw,
  audioEffect: myCustomAudio
})'
```

As for merging in the .wav, it will be exactly the same process, just without the custom draw function.

**Comment by RationalCoding** [comment]
When you remove the stream, you'll need to remove the audio node you added to the destination, otherwise audio will continue. (since the merger has no idea what you've done inside that function). Video will clean up fine.

```javascript
audioSource.disconnect(merger._audioDestination)
```

**Comment by t-mullen** [comment]
You'll need the latest version. I've added a getter for the AudioContext and destination so you don't have to go mucking around in private variables.

**Comment by alectrocute** [comment]
Awesome! Above and beyond explanation. Cheers.

For reference, I’m playing around with Spotify’s API and am trying to build a simple Cordova/Ionic/Angular app that lets the user select a video off their Camera Roll (locally saved, .mp4/.mov), then search through the Spotify API’s results to select a :30 song sample (the .wav/.mp3/.aac file originally mentioned, to be downloaded to temp local storage). Then I’m hoping to use the ionic-native-video-editor API to trim the video down to :30 (user supplies in/out points) and then use your code/examples here to combine both the video with the audio clip and save out a final .MP4/whatever (can be converted with the video-editor API so that’s not a worry).

Seem feasible?

**Comment by alectrocute** [comment]
Assuming the “merging time” will be 1:1, since I have to draw it. Would I be correct in assuming that?

PS - If this *does* work, you should consider advertising such functionality for Cordova/Ionic because it’s highly sought after, after all iOS doesn’t really support the FFMPEG wrappers in my experience.

**Comment by t-mullen** [comment]
That sounds awesome! Seems feasible.

Both merging methods will keep up with the playback of the media element, so they are kept at 1:1. WebAudio naturally does, and the video method is sampling frames so it can't drift.

Merging is realtime because of this, so it will take as long as the video is.

**Comment by RationalCoding** [comment]
If you're merging static resources like that and don't need any MediaStream support, I'd recommend FFMPEG.js instead of this project.

**Comment by t-mullen** [comment]
If you're only using static files, you may want to take a look at FFMPEG.js. I'm not sure if they support merging/composing though.

https://github.com/Kagami/ffmpeg.js?files=1
https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos

**Comment by alectrocute** [comment]
I don’t think it supports merging without some serious hacking in the source dist. And I’m really, really good at breaking things so I was hoping to find a solution that doesn’t involve forking and inevitably breaking. Hah.

**Comment by t-mullen** [comment]
I was wrong about having to manually clean up the audio nodes, that will be done automatically (I guess I've fixed that already.)

Good luck with your project!

**Comment by alectrocute** [comment]
Hey Thomas,

Does FFMPEG.js require the actual full FFMPEG to be installed on the device?

Can I even do that on iOS?

**Comment by t-mullen** [comment]
I'm sure this will be useful to other people, so I've added a convenience function to the module to do this.

Get both files playing in the page (they can be muted) and then just use:
```javascript
var merger = new VideoStreamMerger()

merger.addMediaElement('myMP4', mp4VideoElement)
merger.addMediaElement('myAAC', AACAudioElement)

merger.start()
```

**Comment by t-mullen** [comment]
I think it uses a WebAssembly build of FFMPEG. I wouldn't attempt to build it yourself unless you have a lot of spare time :)

**Comment by alectrocute** [comment]
@RationalCoding That's awesome! Such a convenient module! I pretty much have to try it out now...

And ugh, more reason to stay away from the JS/WebAssembly builds of FFMPEG. I've been looking at https://bgrins.github.io/videoconverter.js/demo/ which is an ancient, and by ancient I mean 3 years old, build of FFMPEG converted to JS via Emscripten. Pretty interesting, except that the minified version of the main .js script is over 20Mb.

**Comment by t-mullen** [comment]
MP4+AAC files being merged: https://rationalcoding.github.io/video-stream-merger/demo/files.html

**Comment by alectrocute** [comment]
![screen shot 2018-01-16 at 5 12 08 pm](https://user-images.githubusercontent.com/35377827/35020340-7a63ac42-fae0-11e7-9276-aac852999139.png)

Attempting to test your demo but getting a promise that's not being resolved :(

Any advice? Is this because I'm not running on a node server?

**Comment by t-mullen** [comment]
I was making an unnecessary call to getUserMedia in the demo code. The error was probably because you have no capture devices on that machine. Fixed now.

**Comment by alectrocute** [comment]
Working wonderfully now, cheers!
