### ISSUE TITLE
is crop work ？

### ISSUE THREAD

**Issue by mike-hor** [t-mullen/video-stream-merger#14]
first thanks for your work,my code have any problem?
I want to implement the cutting function, but it seems that the result is not correct
![image](https://user-images.githubusercontent.com/17822235/35103580-3ec6b234-fca1-11e7-8cd5-c0d3a956966e.png)
result:
![image](https://user-images.githubusercontent.com/17822235/35103746-c46ea054-fca1-11e7-8305-badb63b011e4.png)
it seems just move the screen,but not crop

**Comment by t-mullen** [comment]
What is your merger.width and merger.height?

**Comment by t-mullen** [comment]
To crop, your x,y coordinates have to be negative or zero (to pull the left/top of the image off of the output), and the width/height have to be greater than merger.width and merger.height (to pull the right/bottom off of the output)

Your code is resizing the stream to a small window at the bottom.

Look at index.html in this repo for the demos.

**Comment by mike-hor** [comment]
@RationalCoding thanks, i solved my problem
