### ISSUE TITLE
Low-resolution merged stream

### ISSUE THREAD

**Issue by louiscenter** [t-mullen/video-stream-merger#15]
Hello! Fantastic library, thanks for your hard work!

One thing I'd like to do is be able to merge a `MediaStream` of my screen share (using `screen-record`, as demonstrated in your `README`), and then crop it.

When I merge a screen stream, and then view it in a `<video>` element, it comes out somewhat low-res and pixelated. However, if I view the screen stream directly with the `<video>` element, instead of the merged stream, the resolution appears fine.

I've attached a screenshot to demonstrate the issue.

Is this a `<canvas>` related problem, and is there a potential solution?

![screen shot 2018-01-22 at 12 45 24 am](https://user-images.githubusercontent.com/17946150/35200429-7af29f24-ff0e-11e7-9f79-4b0c539fe4d4.png)

**Comment by t-mullen** [comment]
The output resolution of the merged stream is set by the width and height options you pass to the merger. The defaults are 400x300px. Which is really low resolution (and actually a strange ratio now that I look at it). You can change it to whatever you'd like. Try 1920×1080?

If you set output resolution too high, you'll pay for it with a lower framerate as the merger struggles to keep up. It depends how fast your computer is.

**Comment by t-mullen** [comment]
```javascript
var merger = new VideoStreamMerger({
  width: 1920,
  height: 1080
})
```

**Comment by louiscenter** [comment]
Perfect! Thank you `^__^`
