### ISSUE TITLE
Audio handle question

### ISSUE THREAD

**Issue by HeriBrito** [t-mullen/video-stream-merger#17]
Hi @RationalCoding,

awesome work with video-stream-merger, but i have one question.

I merged some stream (video & audio) with your video-stream-merger, making one unique stream to send by webrtc, but i need to mute and unmute selective of that source stream. I see your code and make a new function for that:

VideoStreamMerger.prototype.muteStream = function (mediaStream, estado) {
  var self = this

  if (typeof mediaStream === 'string') {
    mediaStream = {
      id: mediaStream
    }
  }

  for (var i = 0; i < self._streams.length; i++) {
    if (mediaStream.id === self._streams[i].id) {
      if (self._streams[i].audioOutput) {
        self._streams[i].audioOutput.gain.value = estado ? 0 : 1;
     }

      break;
    }
  }
}

If "estado" is true, set gain.value to 0, otherwise 1. Is this function the correct path?, because i still hear the audio in the other peer. If this function is not correct, how can i handle de audio for the source streams, once has been merged?

Regards

**Comment by t-mullen** [comment]
I suggest using the existing audioEffect option to apply the gainNode.

```JavaScript
function (source, dest) {
   source.connect(gainNode)
   gainNode.connect(dest)
}
```

**Comment by t-mullen** [comment]
See “Custom WebAudio Effects” in the README for more details on this option.

**Comment by HeriBrito** [comment]
Perfect @RationalCoding  ... it's work !!!

Thanks a lot
