### ISSUE TITLE
Bandwidth

### ISSUE THREAD

**Issue by ben-pr-p** [t-mullen/video-stream-merger#2]
Hi - I'd like to use dist/video-stream-merger – would you be interested in publishing it to NPM?

**Comment by ben-pr-p** [comment]
Sorry – didn't notice that you had.

Question – this holds bandwidth constant, regardless of the number (or absence) of streams, correct?

**Comment by t-mullen** [comment]
Yes, streams will be merged into one composite stream with the exact same bandwidth and resolution.

It's actually the same stream, more frames are just being drawn onto the existing video.
