### ISSUE TITLE
black video in chrome v67

### ISSUE THREAD

**Issue by rohityadav1** [t-mullen/video-stream-merger#20]
Hi,
It was working fine while using chrome v66, After updating chrome v67 then it is showing black video.
I have checked this issue in Ubutu 14.04 LTS (64 bit) and windows 10 (64 bit).
![image](https://user-images.githubusercontent.com/16444583/40779679-7d0c4882-64f3-11e8-8a5b-ac9abbb8c606.png)

**Comment by t-mullen** [comment]
Chrome 67 no longer loads videos that aren't attached to the DOM and freezes videos that are not visible.

Fixed in `2.9.1`.
