### ISSUE TITLE
Not working on Windows using Chrome

### ISSUE THREAD

**Issue by dnovicki** [t-mullen/video-stream-merger#21]
I can hotswap streams and it reflects the newly added stream locally but the receiving client still gets the old stream. Any ideas?

**Comment by t-mullen** [comment]
I'm assuming you're using an RTCPeerConnection to send the stream. Are you sure you're adding `merger.result` to the peer?

Any code sample you can provide would help.

**Comment by t-mullen** [comment]
Also, does the P2P demo work for you? https://rationalcoding.github.io/video-stream-merger/demo/p2p.html

**Comment by t-mullen** [comment]
Closing since I can't reproduce this.
