### ISSUE TITLE
Black video on iframe Chrome V.70.0.3538.110 after update

### ISSUE THREAD

**Issue by ppongsakorn** [t-mullen/video-stream-merger#22]
Hi t-mullen,

We found some problem about video merged render on iframe Chrome but work on Firefox.
The video show black screen after update google chrome.

Sample Image
https://drive.google.com/file/d/1DTQu9M7RNvdmBBLJGDjka3g4tauyNE77/view?usp=sharing

Thank you.
Pongsakorn.

**Comment by t-mullen** [comment]
iFrames will only load video elements with non-zero widths and heights. Normal pages don't have this limitation, so I've no idea why iFrames do.

Regardless, it's fixed in the latest version.
