### ISSUE TITLE
The option to only merge the audio

### ISSUE THREAD

**Issue by ntnahn** [t-mullen/video-stream-merger#24]
Can you give the option to only merge the audio without video and canvas draw?
Thanks.

**Comment by t-mullen** [comment]
You don't need this module if that's all you want, the WebAudio API supports it natively:

```javascript
const dest = audioCtx.createMediaStreamDestination()
mediaStreams.forEach(mediaStream => {
  const audio = document.createElement('audio')
  audio.srcObject = mediaStream
  audio.autoplay = true
  const source = audioCtx.createMediaElementSource(audio) // mind garbage collection here
  source.connect(dest)
})
dest.stream // output mediastream
```

**Comment by t-mullen** [comment]
Or did you mean you want video merging, but want the option to disable it for some streams?

**Comment by ntnahn** [comment]
> You don't need this module if that's all you want, the WebAudio API supports it natively:
> 
> ```js
> const dest = audioCtx.createMediaStreamDestination()
> mediaStreams.forEach(mediaStream => {
>   const audio = document.createElement('audio')
>   audio.srcObject = mediaStream
>   audio.autoplay = true
>   const source = audioCtx.createMediaElementSource(audio) // mind garbage collection here
>   source.connect(dest)
> })
> dest.stream // output mediastream
> ```


Your above code is what i need, thanks so much.

**Comment by t-mullen** [comment]
Keep in mind your nodes will be garbage collected in the above code - you need to keep a reference to it somewhere.

ie)
```javascript
const dest = window['destNode'] = audioCtx.createMediaStreamDestination()
mediaStreams.forEach((mediaStream, i) => {
  const audio = window['audioElement' + i] = document.createElement('audio')
  audio.srcObject = mediaStream
  audio.autoplay = true
  const source = window['sourceNode' + i] = audioCtx.createMediaElementSource(audio)
  source.connect(dest)
})
dest.stream // output mediastream
```

**Comment by ntnahn** [comment]
> Keep in mind your nodes will be garbage collected in the above code - you need to keep a reference to it somewhere.
> 
> ie)
> 
> ```js
> const dest = window['destNode'] = audioCtx.createMediaStreamDestination()
> mediaStreams.forEach((mediaStream, i) => {
>   const audio = document.createElement('audio')
>   audio.srcObject = mediaStream
>   audio.autoplay = true
>   const source = window['sourceNode' + i] = audioCtx.createMediaElementSource(audio)
>   source.connect(dest)
> })
> dest.stream // output mediastream
> ```

So sorry, i had edited it.
