### ISSUE TITLE
Working with browser getUserMedia getDisplayMedia on chrome

### ISSUE THREAD

**Issue by rohitshetty** [t-mullen/video-stream-merger#25]
Now that chrome natively supports both [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) and [getDisplayMedia](https://www.google.com/search?client=firefox-b-d&q=getdisplaymedia) can we use these directly along with video-stream-merger in latest chrome > 72? Will they work fine?

**Comment by Tryptophan** [comment]
I noticed on the MDN spec for getDisplayMedia audio capture support isn't available for any browser. Does anyone know if that's being worked on a future release on any browser?

**Comment by rohitshetty** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia
Doesn't chrome 72 support it? I updated to latest chrome and tried this: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture 
It worked for me.

**Comment by t-mullen** [comment]
video-stream-merger should work with any MediaStream, I don't think you should have any problem?

**Comment by t-mullen** [comment]
I can confirm it works on Chrome.
