### ISSUE TITLE
Can I change the shape of merging videos?

### ISSUE THREAD

**Issue by rohitshetty** [t-mullen/video-stream-merger#26]
How can I change the default rectangle video stream to say something like a circle? or apply some kind of styling?

**Comment by t-mullen** [comment]
Use the `draw` option to control how frames are drawn. You have access to the entire HTML5 canvas API. For example, here's how to draw a circular frame.

```javascript
merger.addStream(stream, {
  draw: function (ctx, frame, done) {
     x, y, width, height = // decide where you want your circular image, and what size

     ctx.save(); // save canvas context
     ctx.beginPath();
     ctx.arc(x + width/2, y + height/2, width/2, 0, Math.PI*2, true);   // create an circle centered around frame
     ctx.closePath();
     ctx.clip(); // clip the context to the circle
        
     ctx.drawImage(frame, x, y, width, height); // draw the image in the clipped context
     ctx.restore(); // restore canvas context so you don't clip every other stream
     done() // <- you must call this so the merger can continue 
  }
})
```

There's a huge amount of different cropping, styling, and compositing methods available to you.

**Comment by rohitshetty** [comment]
This is so cool! Thanks a lot. 
One last question, what are the performance implication? Is this done one time thing or does this happen to every in flowing frame?

**Comment by rohitshetty** [comment]
Also, Where can I read more about how this library works and media streams in general. This library is soo cool!

**Comment by t-mullen** [comment]
Your draw function will be called every frame. Drawing video frames to canvas is surprisingly performant, it's mostly just copying data over and is GPU-accelerated in most environments.

The README and issues are probably the only resources available about this library. If you feel there's any questions unanswered, feel free to ask them!

Here's a blog post about the captureStream API, which is how this library makes MediaStreams from canvas: https://developers.google.com/web/updates/2016/10/capture-stream
