### ISSUE TITLE
Question: Reordering multiple streams 

### ISSUE THREAD

**Issue by luanraithz** [t-mullen/video-stream-merger#29]
I'm dealing with video position dynamically, as a example, for 4 people in a room, here is a similar code:
```javascript 
  const propsFor4Streams = {
    [Directions.VERTICAL]: (index, containerWidth, containerHeight) => ({
        x: 0,
        y: (containerHeight / 2) * index,
        width: containerWidth / 2,
        height: containerHeight / 2,
    })
    ,
    [Directions.FLEX]: (index, containerWidth, containerHeight) => ({
        x: index % 2 && containerWidth / 2,
        y: index >= 2 ? containerHeight / 2 : 0,
        height: containerHeight / 2,
        width: containerWidth / 2
    })
}
```
One of the 4 people gets the stream merged and send to a streaming service (a machine with a WOWZA running on it) via a webrtc connection:
```javascript
const { result } = this.streamMerger
const tracks = result.getTracks()
console.log(`Adding ${tracks.length} tracks to peer connection`, tracks)
tracks.forEach(track => this.peerConnection.addTrack(track, result))
```

The connection works very nicely, but with a poor performance when I use `streamMerger.result`.
As a test scenario, I used one of the streams inside the video tags that you generated in your code, and in that case it works with a very good performance.
Have you faced anything that looks like this?

Another questions, is there a better way to append a new stream from a new participant in the room?
Every time a user connects, I create the whole merger again, as I must calculate the x,y, width and height for each scenario:
```javascript

this.streamMerger = new VideoStreamMerger({
      width: 720,
     height: 480,
     frameRate: 29,
     ...config
})

const streams = this.getAllCurrentStreams()
// The compute streams size is where I have a switch case for every scenario
computeStreamsSize(streams).map(({ stream, props }) => this.streamMerger.addStream(stream, props))
this.streamMerger.start()
```

With this code, the stream in the peer connection stop working, right?
The question is the same, is there a better way to do it all?

**Comment by luanraithz** [comment]
I ended up just removing every single stream and adding them all again with the right props, it works but the performance it not that good

**Comment by t-mullen** [comment]
If you want dynamic positioning/sizing of streams, use the `draw` option instead of the `x/y` and `height/width` options.

```javascript
merger.addStream(mediaStream, {
  draw: function (ctx, frame, done) {
    ctx.drawImage(frame, x, y, width, height) // x,y,width,height can be changed as you want, without re-adding the stream
    done()
  })
})
```

So the page running slow when you add `merger.result` to a peer connection, but not if you add it to a video element?

**Comment by luanraithz** [comment]
Not exactly, when I add `merger.result` to a peer connection it goes very slowly, but if I get the srcObject from a video element that you library created, and add it to the peer connection (instead of the `merger.result` ), it goes just ok.
I may test it more and give you some more feedback about it.

**Comment by luanraithz** [comment]
That's what I'm trying to do:
```javascript
// When I tried with the following line
const { srcObject } = this.videoElement // which is the same as this.streamMerger.result
// with the line above the stream on the other peer (wowza server) is very poor, sometimes it stops for no reason

// I also tryied with just the current user stream, this way the stream goes very nice
const srcObject = this.localParticipantStream

const tracks = srcObject.getTracks()
// add tracks to peer connection...
```

**Comment by t-mullen** [comment]
Can you try sending `merger.result` to another browser peer (not a Wowza peer) so we can rule out this being a problem with Wowza.

**Comment by luanraithz** [comment]
Okay I will try it

**Comment by t-mullen** [comment]
Even playing `merger.result` in a video element and seeing how that runs would help diagnose your performance issues.

**Comment by luanraithz** [comment]
I couldn't test it yet, but adding `merger.result` into a video's `srcObject` works fine.

**Comment by t-mullen** [comment]
I'm not sure this is a VSM issue. I've sent `merger.result` over WebRTC on an older laptop without any noticeable performance problems.

Feel free to re-open if you find a way to reproduce.

**Comment by luanraithz** [comment]
Okay, thanks for your time
