### ISSUE TITLE
DataChannel support?

### ISSUE THREAD

**Issue by carboniris** [t-mullen/video-stream-merger#3]

**Comment by t-mullen** [comment]
You want to merge data channels? Use a multiplexer.

This module only covers MediaStreams.

https://github.com/maxogden/multiplex
https://github.com/dominictarr/mux-demux

**Comment by carboniris** [comment]
No, I want to merge media streams with an existing DataChannel connection. The use case is for a text chat application where the user can opt-in to voice and video, but I'd like to avoid manually renegotiating if possible.

**Comment by t-mullen** [comment]
The data stream and media stream are completely separate. Just add the output MediaStream to your pc before you connect, then add streams whenever you want.

If you're using SimplePeer:
```javascript
var merger = new VideoStreamMerger()
merger.start()
var peer = new SimplePeer({
  stream: merger.result
})
// later, do merger.addStream (no renegotiation required)
```

**Comment by t-mullen** [comment]
If you're not using SimplePeer, it'd be something like this:

```javascript
pc.addStream(merger.result)
pc.createDataChannel(name, config) // create data channels as you were before
// merger.addStream whenever you want
```

Your datachannel code won't be affected.

**Comment by carboniris** [comment]
Oh, ok, awesome! That's​ exactly what I needed.
