### ISSUE TITLE
Question: Multiple VideoStreamMerger to play in sync?

### ISSUE THREAD

**Issue by AmeDin** [t-mullen/video-stream-merger#30]
Hi 

I was wondering:

1) if its possible to sync the play between multiple VideoStreamMerger on a page?

2) Or one VideoStreamMerger to display something like
Let say [100% x 100%] as showing the full screen of the video. 
I would like the video to show
[50% x 50%] [white area(probably 10%)] [50% x 50%]
so its cropped 50% followed by some white area, then the other 50%.

I hope you understand what i'm trying to achieve here :)

**Comment by t-mullen** [comment]
1) The mergers run in realtime, so you shouldn't need to sync them up as long as your input streams aren't out of sync. I don't recommend running more than one merger if you can avoid it though.

2) I'm not quite sure what kind of layout you want (maybe you could draw a picture?), but you can probably do it. Take a look at "Custom Draw Function" in the README and the HTML5 canvas. It should cover everything you want.

**Comment by AmeDin** [comment]
Please find the image below for what i'm fiddling with. 

I have created 5.... merger lol.. currently im doing a loop to initiate a merger.start.. which the videos are now playing at milliseconds to seconds difference. I noted that i shouldn't be running be running more than one, so i'm trying to to #2, custom draw. Is it possible to draw something like this? (the 4 videos at the are cropped areas of the middle video.)

![img](https://user-images.githubusercontent.com/22016459/56636634-f7828180-669b-11e9-8041-63780aee02a2.png)

**Comment by t-mullen** [comment]
Sure, that's definitely possible with just one merger. I tweaked the demo to use your layout:

```javascript
// define where you want your center video to be, and what dimensions
const centralVideo = {
  x: merger.width * 1/3,
  y: merger.height * 1/3,
  height: merger.height*1/3,
  width: merger.width*1/3
}
// define what size you want your 4 cut-up videos to be and where
const otherVideos = {
  width: merger.width * 1/3,
  height: merger.height * 1/3,
  x: [0, merger.width - merger.width * 1/3], // x coordinates of both columns
  y: [0, merger.height - merger.height * 1/2] // y coordinates of both rows
}
merger.addMediaElement('mp4', mp4Element, { // or addMediaElement
  draw: function (ctx, frame, done) { // <- custom draw function
    if (!frame.videoWidth) return done() // <- need to wait for video element to load

    // draw the full frame in the center (easy part)
    ctx.drawImage(frame, centralVideo.x, centralVideo.y, centralVideo.width, centralVideo.height)

    // draw the cut-up parts in each corner
    otherVideos.x.forEach((colX, i) => { // loop over columns
      otherVideos.y.forEach((rowY, j) => { // loop over rows
        // this defines what part of the frame you're drawing
        const [sx, sy, sWidth, sHeight] = [i*frame.videoWidth/2, j*frame.videoHeight/2, frame.videoWidth/2, frame.videoHeight/2]

         // this defines where you're drawing that part
        const [dx, dy, dWidth, dHeight] = [colX, rowY, otherVideos.width, otherVideos.height]
        ctx.drawImage(frame, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight)
      })
    })
    done()
  }
})
```

Here's what this gives me:
<img width="445" alt="Screen Shot 2019-04-24 at 2 55 30 AM" src="https://user-images.githubusercontent.com/14932492/56638556-79db5900-663c-11e9-8426-c0e9a878fdf9.png">

Rest of the demo code: https://gist.github.com/t-mullen/df3cf9f3313ddfc74067a26f00f8a9ae

**Comment by AmeDin** [comment]
I tried the draw function but i notice that it doesn't play the video. It just show the image at the starting frame upon playing. 

![image](https://user-images.githubusercontent.com/22016459/56640634-15ed7a80-66a6-11e9-840d-9b14bc38f53a.png)

The video needs to playing like below.. below is my current 5 merger.. 

![mygif](https://user-images.githubusercontent.com/22016459/56641132-3833c800-66a7-11e9-816e-c9b0849ff748.gif)

**Comment by t-mullen** [comment]
Do you have `videoElement.autoplay = true` on both input and output video elements?

**Comment by AmeDin** [comment]
Yes, they are both set to true.

The demo in the link here
https://t-mullen.github.io/video-stream-merger/demo/files.html
also seems to be showing the image at the certain frame. 
original sample.mp4 seems to be playing, ie the tank gun moving but the demo video is stuck at one frame only.

**Comment by t-mullen** [comment]
You're right, try calling `videoElement.play()` after `videoElement.autoplay = true`. It seems to fix the issue of the input video not playing.

**Comment by AmeDin** [comment]
It works. Thanks for the help and quick response to the query :) 👍
