### ISSUE TITLE
Video currentTime not working

### ISSUE THREAD

**Issue by AmeDin** [t-mullen/video-stream-merger#31]
Hi Thomas,

The ability to manipulate html5 video property for currentTime when media is played with the merger

1# The time increments despite video looped.
2# I am unable to set the currentTime of the video. 

I would need to be able to manipulate the currentTime of the media that is played with the merger such as getting the correct currentTime and setting to specific time of the video

**Comment by t-mullen** [comment]
Are you trying to set currentTime on a video playing the merger output or a video the merger is taking as input?

```javascript
merger.addMediaElement(video)
video.currentTime = x
```
or
```javascript
video.srcObject = merger.result
video.currentTime = x
```

**Comment by AmeDin** [comment]
Lets use your demo for the example
https://t-mullen.github.io/video-stream-merger/demo/files.html

Upon clicking start the sample.mp4 plays and keep looping. The actual length of the video is 5 second.
On google console, i try to retrieve the currentTime with
`document.getElementById("output").currentTime`

This will retrieve how long the video has been running, but not the actual time of the video. (Actual video is 5 second). 

Answering to the question you have for more info,
I will need to set the time when the video is playing.
`document.getElementById("output").currentTime = 3` 

For my requirement
I'll need to get the currentTime of the video which is 0-5 second. 
and also have the ability set the currentTime which is similar to
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_av_prop_currenttime

**Comment by t-mullen** [comment]
The output is a live MediaStream, so you won't be able to scrub it (change currentTime). `currentTime` for video elements playing MediaStreams is read-only and will only ever display the running time of the live stream. 

If you want to change the current position of the merger output, you have two options:

1) Change the current position of all the inputs. So, to move the output video back 5 seconds, you'll need to instead move all of the input videos back 5 seconds. However, this won't undo any layout changes you made through the merger during that time.

2) Record the output stream so you can scrub it. Basically record webm chunks and feed them into the MediaSource API. This is more involved and you'll see some latency, but it'll achieve what you want. I have a repo that should simplify this:
https://github.com/t-mullen/mediastream-to-webm
```javascript
const encoder = mtw.EncodedStream(merger.result) // records the MediaStream into WebM
const decoder = mtw.DecodedStream() // loads WebM into a video element
encoder.pipe(decoder) // connect the two

// you now have a video element that can play any point in the stream
const scrubbableVideo = decoder.videoElement
scrubbableVideo.autoplay = true
scrubbableVideo.oncanplay = function () {
    scrubbableVideo.play() 
    scrubbableVideo.currentTime = 5 // <- this will work now
}
```

**Comment by AmeDin** [comment]
Apologies for the late reply. Finally find some time to resume tinkering with my development.

As for #1, I'd like to confirm what you meant by changing the current time of the input. Please correct me if i interpret it wrongly. To remove the stream of the video merger with .removeStream(), followed by adding a new stream with input video object currentTime altered to the position that i want. Then query output element put in the new .result for the srcObject. <- This works

#2, I've yet try this method. Will give a try after further regression on #1 to my requirement. 

Will reach out to you again if i find difficulties implementing #2. 

Really appreciate your help, video-stream-merger is awesome stuff!

**Comment by t-mullen** [comment]
I think you've got it.
```javascript
// add your inputs, setup your output video
merger.addMediaElement(inputVideo)
merger.addMediaElement(inputVideo2)
outputVideo.srcObject = merger.result

// then, when you want to change position of video
function setCurrentTime(t) {
  inputVideo.currentTime = t
  inputVideo2.currentTime = t
 // this is equivalent* to outputVideo.currentTime = t
 // (which doesn't work due to merger.result being live)
}
```

*Keep in mind this won't undo any merger state, just the input state.

**Comment by t-mullen** [comment]
I hope I could answer your question. Please reopen if that's not the case.
