### ISSUE TITLE
Flip and merge a stream

### ISSUE THREAD

**Issue by omar94f** [t-mullen/video-stream-merger#40]
How do I flip a video horizontally such that it is mirrored? I only want to mirror one video in the canvas, not sure how to achieve that.

**Comment by t-mullen** [comment]
You'll need to write a custom draw function.

```javascript
merger.addStream(mediaStream, {
  draw: function (ctx, frame, done) {
    // You can do whatever you want with this canvas context
    ctx.translate(merger.width, 0);
    ctx.scale(-1, 1);
    ctx.drawImage(frame, 0, 0, merger.width, merger.height);
    done()
  })
})
```

https://stackoverflow.com/questions/3129099/how-to-flip-images-horizontally-with-html5

**Comment by selva2242** [comment]
I Need to mirror the video, I used the above code for fliping, But the result was not as expected, the resultant video is blinking
 merger.addStream(videoStream, {
          draw: function (ctx, frame, done) {
              ctx.translate(video.videoWidth, 0);
              ctx.scale(-1, 1);
              ctx.drawImage(frame, 0, 0, video.videoWidth, video.videoHeight);
              done()
          }, 
          x : 0,
          y : 0,
          mute : false,
}
Any thoughts on this
