### ISSUE TITLE
Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track

### ISSUE THREAD

**Issue by samarthagrawal2797** [t-mullen/video-stream-merger#41]
Hi @t-mullen,

I am trying to use it with getDisplayMedia() for screen capture but I keep getting this error "**Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track**". Can you please assist me on how to solve it?

**Comment by t-mullen** [comment]
Try `mute:true` in the addStream options.

**Comment by samarthagrawal2797** [comment]
Thanks, @t-mullen it worked for me.
