### ISSUE TITLE
audio and video are not synchronous

### ISSUE THREAD

**Issue by lucasfischer** [t-mullen/video-stream-merger#42]
First of all thank you for this library. Makes working with MediaStreams much easier.

I implemented this in an app but some users reported and showed me that videos that get recorded this way have a delayed video stream. My guess is that this happens due to the usage of the canvas element that gets recorded. If i record the video stream directly without a canvas or this library there is no audio/video delay.

Is anyone experiencing the same or knows how to fix this?

**Comment by t-mullen** [comment]
One way to mitigate this is by introducing an audio delay:
```javascript
const delayInSeconds = 0.02
merger.addStream(mediaStream, {
  audioEffect: function (sourceNode, destinationNode) {
     delayNode = merger.getAudioContext().createDelay(5.0)
     delayNode.delayTime.setValueAtTime(delayInSeconds, merger.getAudioContext().currentTime)
     sourceNode.connect(delay)
     delay.connect(destinationNode)
  })
})
```

The length of this delay changes depending on how fast the client is processing frames, which makes things significantly more complicated (requiring you to time `requestAnimationFrame`, adjust delay based on the expected frame duration, and re-build the delay nodes.)

This is something I've been meaning to add in-module.

**Comment by t-mullen** [comment]
You should only notice this with either a very low-performance client (phones) or with a lot of video streams. Let me know if this is not the case.

**Comment by t-mullen** [comment]
`v3.3.2` introduces audio delay proportionate to the video processing delay.

Please reopen if this doesn't solve your issue.

**Comment by lucasfischer** [comment]
Hey @t-mullen I just wanted to come back and say that the new update is working great. Using this since 3 weeks in production now and did not have a single complaints or problems since then. Genius fix.

Thank you very much.
