### ISSUE TITLE
removeStream() and addStream() throw error since version 3.3.2

### ISSUE THREAD

**Issue by lucasfischer** [t-mullen/video-stream-merger#43]
Thank you for the 3.3.2 update. I wanted to try it out but since the update i get the following error when calling `removeStream()` and `addStream()`:

```
client.js?06a0:77 Error: "i" is read-only
    at _readOnlyError (video-stream-merger.js?a366:formatted:56)
```

My assumption is that it might have something to do with the variable decelerations you changed from `var` to `let` in the for-loops.

**Comment by t-mullen** [comment]
Bad NPM publish - this is what happens without coffee.

Use `v3.3.3`
