### ISSUE TITLE
is it possible to change height and width of a stream while recording?

### ISSUE THREAD

**Issue by scgm11** [t-mullen/video-stream-merger#45]
example recording a stream of a mobile phone that goes from landscape to portrait and can change anytime

**Comment by t-mullen** [comment]
`v3.4.0` adds `merger.setOutputSize(width, height)`, which should cover this usecase.

See README for more details.

**Comment by scgm11** [comment]
this is changing the merger output size, but for this use case I think I have to change each of the added stream sizes

**Comment by t-mullen** [comment]
So getUserMedia is giving you a landscape stream, and when you rotate the phone, it stays sideways?

You can rotate the landscape stream to become portrait with a custom `draw` function.

**Comment by scgm11** [comment]
let me explain it better:

each time the other side (mobile) changes portrait to landscape I have a message so I can change video settings, Im gonna show you the code I have now and the result video 

```javascript
  rotateRecording(isportrait) {

    let width;
    let height;

    if(isportrait) {
      width = 360;
      height = 640;
    } else {
      width = 640;
      height = 360;
    }
    this.merger.setOutputSize(width, height);
  }
```


[recording (2).webm.zip](https://github.com/t-mullen/video-stream-merger/files/4568736/recording.2.webm.zip)
