### ISSUE TITLE
Use the video stream merger in node.js

### ISSUE THREAD

**Issue by finnscho** [t-mullen/video-stream-merger#47]
Hi, 
This is not really an issue. I just didn't know how to contact you.
First thank you for your hard work on the video stream merger. 
I am using the video stream merger to merge multiple recorded videos with different sizes and positions to a single video. Unfortunately, I get performance issues on older devices and ios devices, so I decided to merge the videos in a firebase function (node.js). I have the URLs and coordinates of the recorded videos. Is it possible to create a merged video in node.js? I am struggling to create a Media Stream. Is this possible? 
Thank you & best regards

**Comment by t-mullen** [comment]
This library uses native browser APIs so won't work in Node.js without significant changes.
