### ISSUE TITLE
destroy merger

### ISSUE THREAD

**Issue by scgm11** [t-mullen/video-stream-merger#48]
Im having an issue that starting video merger creates video elements on the DOM but destroy wont remove them. Is it ok to remove them on destroy? if it is I can create a PR.

**Comment by scgm11** [comment]
?

**Comment by t-mullen** [comment]
Yes, all video elements should be cleaned up on destroy. Feel free to make a PR or I will fix this.

**Comment by sagoncalves** [comment]
This stills not solved at latest commit

**Comment by t-mullen** [comment]
Destroy order was incorrect, fixed in `3.6.1`

**Comment by sagoncalves** [comment]
Thanks, now its working.
