### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by t-mullen** [t-mullen/video-stream-merger#5]
@tvedtorama Moved from [simple-peer#50](https://github.com/feross/simple-peer/issues/50)

> @RationalCoding I think your library looks like a promising solution for this problem, but I have a few questions:
> 
> Is the merging logic supported on the browsers that support WebRTC or just on Chrome?

> Could you publish the source for your demo, I can't find it?

> Is it possible to detect that there are "no streams in the merged stream"? Ie - that the host is currently not transmitting anything?
> I guess this could be sent alongside the stream, on the data channel, but anyways...

**Comment by t-mullen** [comment]
I've tested this library on Chrome and Firefox. I can't see why it wouldn't work on other browsers. All that's required is the Canvas API, WebAudio API, and of course WebRTC. 

The P2P demo is here: https://github.com/RationalCoding/video-stream-merger/blob/gh-pages/p2p.html
And the general demo here: https://github.com/RationalCoding/video-stream-merger/blob/gh-pages/index.html

There is no way to tell. There will always be one video track and one audio track regardless of how many streams you merge. You'll have to use the data channel :/

**Comment by tvedtorama** [comment]
Thank you for this feedback!

You also have this excellent example with a canvas, drawing overlays, etc.  Would it be possible to define a high res stream and allow the user to put "things" into it - like their webcam stream, images and hand-written scribbles - and then recompress the result for webrtc transfer?

Are we free to define the resolution of the stream?

Does this "mixing" draw lots of CPU resources, or is it handed over to dedicated hardware (on modern computers)?

**Comment by t-mullen** [comment]
You could use the `draw` option in the `addStream` method to draw things. It provides you an HTML5 canvas context that you can do whatever with (just don't forget to draw your frame). In terms of treating images as streams, I really like that idea. We could pass arbitrary data as the "frame" and draw it without needing any input MediaStream at all.

Yes. The resolution of the output stream is set in pixels with the `width` and `height` options in the merger constructor.

The mixing is done via canvas, so it should be hardware accelerated (GPU).

**Comment by tvedtorama** [comment]
Thank you, I'm very much looking forward to testing this out.  Great work!
