### ISSUE TITLE
Merging addStream with addMediaElement

### ISSUE THREAD

**Issue by nakamigo** [t-mullen/video-stream-merger#55]
Thank you for this really awesome library, works flawlessly!
Recently I decided to merge the webcam stream with some prerecorded video
I would like to place such video at the left bottom corner of the entire frame (similar to Loom)
```javascript
// my webcam feed acting as a background
merger.addStream(camera, { x: 0, y: 0, width: 1366, height: 768 });
// video I want to place in the corner of webcam feed in the form of a circle
merger.addMediaElement('circle', document.getElementById('video'), {
  draw: (ctx, frame, done) => {
    // video size is 1280x720, I need only a circle in the center of it
    const x = 0, y = 0, width = 1280, height = 720;
    ctx.beginPath();
    ctx.arc(x + width/2, y + height/2, width/2, 0, Math.PI*2, true);
    ctx.closePath();
    ctx.clip();
    ctx.drawImage(frame, x, y, width, height);
    ctx.restore();
    done();
  }
});
```
This gives me just a large circle in the center of main frame with video overlayed on top of webcam
Looks like this code has clipped the whole merger frame not only the video frame

Similar to this but everything outside a circle is black: 
![image](https://user-images.githubusercontent.com/66538710/90548868-0bae9400-e1a7-11ea-806e-83063a35d103.png)

Could you please explain what is `ctx` and `frame` when I use `draw` for `addMediaElement`?
I would be obliged if you could point me into the correct direction for achieving my goal!

**Comment by t-mullen** [comment]
You're close, just save the state before clipping:

```javascript
// my webcam feed acting as a background
merger.addStream(camera, { x: 0, y: 0, width: 1366, height: 768 });
// video I want to place in the corner of webcam feed in the form of a circle
merger.addMediaElement('circle', document.getElementById('video'), {
  draw: (ctx, frame, done) => {
    // video size is 1280x720, I need only a circle in the center of it
    const x = 0, y = 0, width = 1280, height = 720;
    ctx.save(); // <--
    ctx.beginPath();
    ctx.arc(x + width/2, y + height/2, width/2, 0, Math.PI*2, true);
    ctx.closePath();
    ctx.clip();
    ctx.drawImage(frame, x, y, width, height);
    ctx.restore();
    done();
  }
});
```

**Comment by nakamigo** [comment]
Thank you so much, I was able to draw it in a small circle at the top left corner of webcam feed
```javascript
draw: (ctx, frame, done) => {
  const x = 0, y = 0, width = 320, height = 185;
  ctx.save();
  ctx.beginPath();
  // 50 pixels from top and left borders
  ctx.arc(height/2 + 50, height/2 + 50, height/2, 0, Math.PI*2, true);
  ctx.closePath();
  ctx.clip();
  ctx.drawImage(frame, x, y, width, height);
  ctx.restore();
  done();
}
```
But how to place it at the bottom left corner of the main frame?
Changing arguments to `drawImage` wasn't helpful, possibly I should also change `arc` but how?
Since I have a circular video, I would need `50 pixels + radius` from left and bottom borders.

**Comment by t-mullen** [comment]
You're drawing your arc in the top-left, you'll have to draw it in the bottom-left, something like:
```javascript
  ctx.arc(height/2 + 50, merger.height - (height/2 + 50), height/2, 0, Math.PI*2, true);
```

**Comment by nakamigo** [comment]
Thank you, Thomas! Works flawlessly now!

By the way, could you please point me how could I update `addMediaElement` if I will change video.src?
Say I want to display several short videos in a row using the same video tag.
Currently it shows only the first video, since it was initialized inside `getUserMedia`.
Is it possible to somehow send a signal to merger that `addMediaElement` source has been changed?

**Comment by t-mullen** [comment]
I think it will just automatically update if you change video.src. Let me know if that's not the case.

**Comment by nakamigo** [comment]
Unfortunately that's not the case, please take a look how I am recording it:
```javascript
merger = new VideoStreamMerger({ width: 1366, height: 768 });
navigator
  .mediaDevices
  .getUserMedia({
    audio: true,
    video: {
      aspectRatio: { ideal: 1.7777777778 },
      width: { ideal: 1280, max: 1920 },
      height: { ideal: 720, max: 1080 },
    }
  }).then(camera => {
    merger.addStream(camera, { x: 0, y: 0, width: 1366, height: 768 });
    merger.addMediaElement('circle', document.getElementById('video'), {
      draw: (ctx, frame, done) => {
        const x = 0, y = 0, width = 426, height = 240;
        ctx.save();
        ctx.beginPath();
        ctx.arc(height/2 + 50, merger.height - (height/2 + 50), height/2, 0, Math.PI*2, true);
        ctx.closePath();
        ctx.clip();
        ctx.drawImage(frame, x, merger.height - (height + 50), width, height);
        ctx.restore();
        done();
      }
    });
    merger.start();
    recorder = new MediaRecorder(merger.result, { mimeType: codec });
    recorder.start();
    // usual logic for saving
    recorder.ondataavailable = chunk => {}
```
And while recording I flip the source of video. Next videos play as expected.
I can even hear the sound of the next video when replaying the file recorded using this code.

Moreover, the circular video is shown during the whole time webcam is recorded.
But after playing the first video it seems frozen at the last frame of the first video.

**Comment by nakamigo** [comment]
Thomas, I was able to get the circular video updated using this outside `getUserMedia`:
```javascript
merger.removeStream('circle');
merger.addMediaElement('circle', document.getElementById('video'), {
  draw: (ctx, frame, done) => {
    // same as inside getUserMedia()
  }
});
```
Not sure if this is optimal to do it each time I swap the video source?

**Comment by t-mullen** [comment]
That should be fine.

**Comment by nakamigo** [comment]
Also when removing the stream I can see circle video blinking for a fraction of a second.
It plays the first video, then disappears and then appears with the new video again.

So is it safe to just call `addMediaElement('circle', {})` without prior removing it?
Would it spawn additional media streams or just overwrite the existing with the same name?

**Comment by t-mullen** [comment]
Adding the stream repeatedly without removing it will create new streams and leak memory.

**Comment by nakamigo** [comment]
Got it, Thomas, thank you so much for your support!
