### ISSUE TITLE
Audio time not sync with video when add/remove audio stream

### ISSUE THREAD

**Issue by xiang-valcano** [t-mullen/video-stream-merger#7]
I try publishing a stream to Wowza. Dynamically adding/removing audio stream corrupts Wowza endcoder. Wowza wait for audio stream when I remove audio stream from your merger.

Anyway, I fixed by adding the following code. It forces the merger to always has audio stream. Not sure its a good practice, but it works perfectly in all situations.

```
  // Fixed encoder wrong timing to wowza - pushing empty audio node
  var constantAudioNode = self._audioCtx.createConstantSource()
  constantAudioNode.start()
  constantAudioNode.connect(self._audioDestination)
```

Full code
```
VideoStreamMerger.prototype.start = function () {
  var self = this

  self.started = true
  window.requestAnimationFrame(self._draw.bind(self))

  // Fixed encoder wrong timing to wowza - pushing empty audio node
  var constantAudioNode = self._audioCtx.createConstantSource()
  constantAudioNode.start()
  constantAudioNode.connect(self._audioDestination)

  // Add video
  self.result = self._canvas.captureStream(self.fps)

  // Remove "dead" audio track
  var deadTrack = self.result.getAudioTracks()[0]
  if (deadTrack) self.result.removeTrack(deadTrack)

  // Add audio
  var audioTracks = self._audioDestination.stream.getAudioTracks()
  self.result.addTrack(audioTracks[0])
}
```

Thanks for your good library.

**Comment by t-mullen** [comment]
Great find!

**Comment by t-mullen** [comment]
Can you confirm that `2.4.2` fixes the issue?

**Comment by t-mullen** [comment]
This also fixes #1. Thanks!

**Comment by xiang-valcano** [comment]
Welcome!

**Comment by xiang-valcano** [comment]
Hi, I have new update. 

This solution cause poor audio quality. So, createConstantSource is not consider a good solution.

I solved my problem by getAudioTracks() and enable/disable the tracks on the go.
