### ISSUE TITLE
How to merge the audio from different video streams? 

### ISSUE THREAD

**Issue by ChauncyYinXun** [t-mullen/video-stream-merger#70]
Hi, I am currently using [webex sdk](https://developer.webex.com/docs/sdks/browser) and webex browser sdk is separating audio streams from video streams. something like this: 

`  meeting.on("media:stopped", (media) => {
    // Remove media streams
    if (media.type === "local") {
      document.getElementById("self-view").srcObject = null;
    }
    if (media.type === "remoteVideo") {
      document.getElementById("remote-view-video").srcObject = null;
    }
    if (media.type === "remoteAudio") {
      document.getElementById("remote-view-audio").srcObject = null;
    }
  });`

I am trying to combine different video streams using video stream merger repo. However, I am unable to get audio from "remoteAudio" stream when saving the combined video.  

![image](https://user-images.githubusercontent.com/32704417/120953048-d3e8fb00-c77e-11eb-98ef-06f7379c73a5.png)

![image](https://user-images.githubusercontent.com/32704417/120953124-f2e78d00-c77e-11eb-836f-2d446a186629.png)

As you can see, the combine video stream works perfect. However, the save video stream doesn't have audio. How to get the remote audio? and also the local audio??? Thanks!
![image](https://user-images.githubusercontent.com/32704417/120953543-bf593280-c77f-11eb-8fe1-edb27323134a.png)

**Comment by t-mullen** [comment]
If can hear audio on playback, then it's likely the issue lies with whatever you are using to save the stream.

Closing since this doesn't appear to be an issue with video-stream-merger, but feel free to continue discussion.
