### ISSUE TITLE
upgrade to 4.01 with problems

### ISSUE THREAD

**Issue by superyhee** [t-mullen/video-stream-merger#80]
when i upgrade to 4.01 ,i got the following errors:
video_stream_merger__WEBPACK_IMPORTED_MODULE_4___default.a is not a constructor

**Comment by superyhee** [comment]
resolved

**Comment by En777** [comment]
@superyhee how to resolve?
```var VideoStreamMerger = require('video-stream-merger');  var merger = new VideoStreamMerger()```  VideoStreamMerger is not a constructor

**Comment by hthetiot** [comment]
@En777 

Have you tried:
> const { VideoStreamMerger } = require('video-stream-merger');

How about:
> import { MediaStreamRecorder } from 'video-stream-merger';

P.s don't comment on closed issue, pls.
