### ISSUE TITLE
Stream Stops if you focus out of the tab

### ISSUE THREAD

**Issue by pablo-meyer** [t-mullen/video-stream-merger#9]
Scenario:

Peer1 - Combines and Share Streams
Peer2 - Received Stream
Peer1 - Looses focus on tab, by navigating to another tab or opening another program
Peer2 - Received Stream stops
Peer1 - Focuses to chrome tab that did the sharing
Peer2 - Resumes receiving the stream 

Issue:  Normally, this doesn't happen with WebRtc and Streams, is the issue that the merger is stopped? Is there some way we can continue making the merger work while in the background?

**Comment by t-mullen** [comment]
Chrome throttles background tabs, and I assume this includes canvas animation (which the merger relies on). Certain APIs like WebRTC and media playback aren't throttled (else you could never play music in a background tab).

The chrome://flags "Throttle expensive background timers" might work.

**Comment by pablo-meyer** [comment]
Its not really feasible to ask users to turn on/off a flag for our intended use...

Any other ideas?

Thanks

**Comment by t-mullen** [comment]
No, it's not a solution for production. It could rule out Chrome throttling though.

**Comment by pablo-meyer** [comment]
You think that this doesn't happen with other browsers?

**Comment by t-mullen** [comment]
I was correct, Chrome is throttling the "requestAnimationFrame" timer. Replacing it with a normal timer doesn't seem to work either. Sorry, but nothing can be done, Chrome has intentionally blocked animation timers inside background tabs. :/

I'll leave this open if things change with the Chrome policy in the future.

**Comment by t-mullen** [comment]
Firefox has the same policy, and shows the same behaviour.

**Comment by t-mullen** [comment]
You can try using another Javascript context to keep the timers running. Webworkers and Serviceworkers have been patched, but using [a popup window](https://github.com/RationalCoding/background-timer) or pinging the client from a server using websockets still works.

I'm closing this issue as it can't be fixed within video-stream-merger. There's no way to implement this without timers.

**Comment by t-mullen** [comment]
https://developers.google.com/web/updates/2017/03/background_tabs

**Comment by t-mullen** [comment]
Great news everyone who was affected by this issue: Chrome/Firefox consider tabs with audio playing to be foreground tabs, so video-stream-merger will now play a silent track. This won't have any effect other than showing a subtle volume icon.

Background throttling will not happen and the stream won't freeze! (At least until browsers catch on and fix this...)
